### ISSUE TITLE
option free in omniproto

### ISSUE THREAD

**Issue by Dominic-Preap** [grpckit/omniproto#4]
You docker build is so cool but it would be cooler if I can pass free options in the `omniproto.yaml` file?

I want to have a free option pass in plugin without concat `_out` or can I have any field in Config Struct to accept the option cause I want to pass like `--proto_path=` or ` --plugin=`. 
```go
// GenProtoString generates a protoc command
// from a config
func GenProtoString(config *Config) string {
        ....
	for _, plugin := range config.Plugins {
		b.WriteString(fmt.Sprintf("--%v_out=%v%v%v", plugin.Name, getArgs(plugin), getOutputForPlugin(plugin, config), space))
	}
       ....
```

**Comment by Dominic-Preap** [comment]
another example is in [protoc-gen-doc](https://github.com/pseudomuto/protoc-gen-doc), I want to pass `--doc_opt` options as markdown file but don't know how.

**Comment by aldelucca1** [comment]
This is actually where plugins come in. You can place the `gen-protoc-doc` binary on your `PATH` and then use:
```yaml
plugins:
- name: go
  args: paths=source_relative
- name: doc
  args: xxx
```
This will influence `omniproto` to place the `--doc_out` argument on the command passing args in the expected format

**Comment by Dominic-Preap** [comment]
@aldelucca1 I want to add option as `--doc_opt`  not `--doc_out`, but `plugins` will always return with concat `_out`  which is what I'm not looking for.
